### PR TITLE
feat(config): Add support for disabling WiFi remote impl

### PR DESCRIPTION
**Pull request by david-cermak**
~~Added  `ESP_WIFI_REMOTE_DISABLE` to enable coexistence with esp-extconn within one project~~

* Made `ESP_WIFI_REMOTE` mutually exclusive with `ESP_HOST_WIFI_ENABLED`
* WiFi remote menuconfig is entirely disabled if  `CONFIG_ESP_HOST_WIFI_ENABLED=y`

### CODE REVIEW

**Comment by SohKamYung-Espressif** [comment]
I added this `Kconfig.projbuild` to `examples/wifi/iperf/main` to test it:

```Kconfig
menu "Example Configuration"
    depends on !SOC_WIFI_SUPPORTED

    choice EXAMPLE_IPERF_OFFLOAD
        prompt "External Wireless Connnectivity Component to use"
        default EXAMPLE_IPERF_OFFLOAD_VIA_WIFI_REMOTE
        help
            External component to use to provide external wireless connectivity (Wi-Fi & Bluetooth)

        config EXAMPLE_IPERF_OFFLOAD_VIA_WIFI_REMOTE
            bool "Wifi-Remote"

        # Kconfig for extconn enables it only if SOC_WIRELESS_HOST_SUPPORTED
        config EXAMPLE_IPERF_OFFLOAD_VIA_EXT_CONN
            depends on SOC_WIRELESS_HOST_SUPPORTED
            bool "Ext-Conn"
            select ESP_WIFI_REMOTE_DISABLE

    endchoice

endmenu
```

Observations:

1. Once `CONFIG_ESP_WIFI_REMOTE_DISABLE=y` appears in the `sdkconfig`, it does not seem possible to remove it by running `idf.py menuconfig` again (to switch back to wifi-remote). I have to do a `rm sdkconfig` first.
2. The iperf example for p4 does not build correctly. I am getting this build error:
```
/home/kysoh/esp/gitlab_esp-idf/examples/wifi/iperf/main/iperf_example_main.c: In function 'app_main':
/home/kysoh/esp/gitlab_esp-idf/examples/wifi/iperf/main/iperf_example_main.c:88:5: error: unknown type name 'app_wifi_initialise_config_t'; did you mean 'wifi_init_config_t'?
   88 |     app_wifi_initialise_config_t config = APP_WIFI_CONFIG_DEFAULT();
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     wifi_init_config_t
/home/kysoh/esp/gitlab_esp-idf/examples/wifi/iperf/main/iperf_example_main.c:88:43: error: implicit declaration of function 'APP_WIFI_CONFIG_DEFAULT'; did you mean 'WIFI_INIT_CONFIG_DEFAULT'? [-Wimplicit-function-declaration]
```

Reason is because `wifi_cmd.h` in the wifi-cmd component has this dependency to enable the header:

```
#if CONFIG_ESP_WIFI_ENABLED || CONFIG_ESP_WIFI_REMOTE_ENABLED || CONFIG_ESP_HOST_WIFI_ENABLED
```

All conditions are not met, if wifi-remote is disabled.

Actually, I think the iperf example on master would not build correctly for P4 because of this.

**Comment by mantriyogesh** [comment]
> Once CONFIG_ESP_WIFI_REMOTE_DISABLE=y appears in the sdkconfig, it does not seem possible to remove it by running idf.py menuconfig again (to switch back to wifi-remote). I have to do a rm sdkconfig first.

This should have some workaround as we discussed. This is issue of sdkconfig itself.

> #if CONFIG_ESP_WIFI_ENABLED || CONFIG_ESP_WIFI_REMOTE_ENABLED || CONFIG_ESP_HOST_WIFI_ENABLED

We might want to add EXT_CONN specific symbol in this list. So that the build goes through for non-wifi-remote. Once confirmed, we can propose the change to concerned repo maintainer..

**Comment by mantriyogesh** [comment]
> This should have some workaround as we discussed. This is issue of sdkconfig itself.

Workaround is also not working fine, it is only till the time we do not exit from sdkconfig. 
if we 'select WIFI-REMOTE-DISABLED' and exit from menuconfig, but re-configure again using `idf.py menuconfig`  and  'enable' again, it shows in menuconfig gui, it enabled again. But in sdkconfig.h or sdkconfig it is still 'WIFI-REMOTE-DISABLED' and not reverted. So the problem is still there

**Comment by SohKamYung-Espressif** [comment]
> We might want to add EXT_CONN specific symbol in this list. So that the build goes through for non-wifi-remote. Once confirmed, we can propose the change to concerned repo maintainer..

Yes, if I change that check to

`#if CONFIG_ESP_WIFI_ENABLED || CONFIG_ESP_WIFI_REMOTE_ENABLED || CONFIG_ESP_HOST_WIFI_ENABLED || CONFIG_ESP_EXT_CONN_ENABLE`

Iperf compiles with ext-conn.

**Comment by david-cermak** [comment]
Updated per offline discussion with @SohKamYung-Espressif to disable WiFi-remote whenever ` ESP_HOST_WIFI_ENABLED` is `ON`. (also added a "read-only" item indicating that it's disabled and describing why)

**Comment by SohKamYung-Espressif** [comment]
LGTM. Tested with building iperf for P4.

By default, `idf.py build` builds and links in wifi-remote and ESP-Hosted.

Running `idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.ci.esp32p4_with_extconn" build` links in ext-conn as expected, so CI with ext-conn should not be affected.

**Comment by mantriyogesh** [comment]
This change would make life extremely easy @david-cermak , thanks a lot.
As it is tested now, with multiple alternatives locally, can we push this change?

Dependent IDF MR would then come to conclusion then.

**Comment by david-cermak** [comment]
> As it is tested now, with multiple alternatives locally, can we push this change?

Published as [`v0.4.1`](https://components.espressif.com/components/espressif/esp_wifi_remote/versions/0.4.1)

Thanks for your inputs and diligent testing!

**Pull request merged**
